apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-spring
  template:
    metadata:
      labels:
        app: java-spring
    spec:
      containers:
        - name: java-spring
          image: ghcr.io/pnvnd/java-spring:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: java-spring
spec:
  selector:
    app: java-spring
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
